module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#FFFFFF",
        "surface-dim": "#F0F4F7",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F8FAFB",
        "surface-container": "#F0F4F7",
        "surface-container-high": "#E1E6EB",
        "surface-container-highest": "#D1D8E0",
        "on-surface": "#1A1C1E",
        "on-surface-variant": "#3D4551",
        "inverse-surface": "#1A1C1E",
        "inverse-on-surface": "#FFFFFF",
        "outline": "#71767A",
        "outline-variant": "#A9AEB1",
        "surface-tint": "#162E51",
        "primary": "#162E51",
        "on-primary": "#FFFFFF",
        "primary-container": "#E2E9F3",
        "on-primary-container": "#0B182B",
        "inverse-primary": "#73B3E7",
        "secondary": "#D83933",
        "on-secondary": "#FFFFFF",
        "secondary-container": "#FCEBEA",
        "on-secondary-container": "#57110E",
        "tertiary": "#73B3E7",
        "on-tertiary": "#000000",
        "tertiary-container": "#EAF3FC",
        "on-tertiary-container": "#102638",
        "error": "#D9381E",
        "on-error": "#FFFFFF",
        "error-container": "#F7E8E6",
        "on-error-container": "#8A1200",
        "primary-fixed": "#162E51",
        "primary-fixed-dim": "#0E1F36",
        "on-primary-fixed": "#FFFFFF",
        "on-primary-fixed-variant": "#E2E9F3",
        "secondary-fixed": "#D83933",
        "secondary-fixed-dim": "#A32520",
        "on-secondary-fixed": "#FFFFFF",
        "on-secondary-fixed-variant": "#FCEBEA",
        "tertiary-fixed": "#73B3E7",
        "tertiary-fixed-dim": "#498CC4",
        "on-tertiary-fixed": "#000000",
        "on-tertiary-fixed-variant": "#EAF3FC",
        "background": "#FFFFFF",
        "on-background": "#1A1C1E",
        "surface-variant": "#F0F4F7",
      },
      fontFamily: {
        "headline-xl": ["Merriweather"],
        "headline-lg": ["Merriweather"],
        "headline-md": ["Merriweather"],
        "body-lg": ["Nunito"],
        "body-md": ["Nunito"],
        "label-md": ["Nunito"],
      },
      fontSize: {
        "headline-xl": [
          "40px",
          {
            lineHeight: "48px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "headline-md": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "0em",
            fontWeight: "600",
          },
        ],
        "body-lg": [
          "18px",
          {
            lineHeight: "28px",
            letterSpacing: "0em",
            fontWeight: "400",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "24px",
            letterSpacing: "0em",
            fontWeight: "400",
          },
        ],
        "label-md": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0.02em",
            fontWeight: "600",
          },
        ],
      },
      borderRadius: {
        "sm": "2px",
        "DEFAULT": "4px",
        "md": "4px",
        "lg": "4px",
        "xl": "8px",
        "full": "9999px",
      },
      spacing: {
        "unit": "8px",
        "container-max": "1040px",
        "gutter": "32px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
    },
  },
};
